/* eslint-disable no-unused-vars */
/* eslint-disable @typescript-eslint/no-unused-vars */
interface Player {
    id: string
    anticapitalism: number
    baseThirst: number
    buoyancy: number
    chasiness: number
    coldness: number
    continuation: number
    divinity: number
    groundFriction: number
    indulgence: number
    laserlikeness: number
    martyrdom: number
    moxie: number
    musclitude: number
    name: string
    bat: string
    omniscience: number
    overpowerment: number
    patheticism: number
    ruthlessness: number
    shakespearianism: number
    suppression: number
    tenaciousness: number
    thwackability: number
    tragicness: number
    unthwackability: number
    watchfulness: number
    pressurization: number
    totalFingers: number
    soul: number
    deceased: boolean
    peanutAllergy: boolean
    cinnamon: number
    fate: number
    armor: string
    ritual: string
    coffee: number
    blood: number
    permAttr: Array<string>
    seasAttr: Array<string>
    weekAttr: Array<string>
    gameAttr: Array<string>
    hitStreak: number
    consecutiveHits: number
    baserunningRating: number
    pitchingRating: number
    hittingRating: number
    defenseRating: number
}